### ISSUE TITLE
Lagra information om samtycke av lagring för GDPR

### ISSUE THREAD

**Issue by jonatanskogsfors** [LinkopingsStudentspex/internsidor#13]
Har spexet hunnit tänka till om GDPR? Jag misstänker att alla nya och gamla medlemmar borde ge någon form av samtycke för att spexet sparar kontaktuppgifter. Vidare borde det finnas rutiner för att kunna bli bortplockad (eventuellt bara kontaktuppgifter om spexet vill kunna ha kvar historisk information över grupper).

**Comment by Karlinde** [comment]
#5 har redan löst lite av den problematiken då personer kan styra hur mycket av deras info som visas för andra. Det vore dock bra att lagra samtyckeshandlingen med en timestamp för att kunna bevisa att samtycke har givits. Det behövs det skapas någon sorts funktion för.

**Comment by Karlinde** [comment]
Jag öppnade den här igen för att jag tycker ändå vi behöver ha någon sorts funktion för att kunna visa att en person har samtyckt till behandling av sina personuppgifter.

**Comment by Karlinde** [comment]
Efter lite ytterligare funderingar och efterforskningar så tror jag inte det är nödvändigt för oss att dokumentera några samtyckeshandlingar här. Det är bara nödvändigt ifall vi skulle basera vår användning av personuppgifter på samtycke, men vårt medlemsregister anser jag istället kan baseras på en s.k. [intresseavvägning](https://www.datainspektionen.se/lagar--regler/dataskyddsforordningen/rattslig-grund/intresseavvagning/). Jag har fixat lite dokumentation som motiverar det för de olika kategorierna av personuppgifter, tänkte ladda upp det på wikin snart.

**Comment by Rovanion** [comment]
Hej,
Jag tänkte inte på det här tidigare när jag läste det här ärendet. Men jag
vill nu minnas att vi vid GDPR:s införande konstaterade att
medlemsregestret faller under en intresseavvägning eftersom den är
nödvändig för driften av föreningen. Så jag här helt med dig KarlL om att
vi inte behöver be om eller spara någon information kring samtycke om att
vi sparar personuppgifter i medlemsmatrickeln (vilket tydligen är korrekt
svenska).

Bland andra tankar undrar jag var dokumentationen tog vägen från våra
styrelsemöten om det här. Men det är garanterat så att jag missminner mig
eller att det helt enkelt var mitt ansvar att dokumentera och att jag
aldrig gjorde det :/
