### ISSUE TITLE
Användarens publika profil bör ange nuvarande medlemsstatus

### ISSUE THREAD

**Issue by Rovanion** [LinkopingsStudentspex/internsidor#20]
Medlemmar undrar ofta huruvida de betalt medlemsavgift eller inte. Detta brukade noteras i batadasen varpå det dök upp på lite olika ställen på internsidorna, bland annat på sidan med användarinformation som andra användare ser: https://old.studentspex.se/visa.php?medlemsnummer=1056

**Comment by Karlinde** [comment]
Löst i c935d5a7c32ca52e719552065f9886512bdc6c48
