### ISSUE TITLE
Föreställningsräknaren visar inte tidigare val

### ISSUE THREAD

**Issue by jonatanskogsfors** [LinkopingsStudentspex/internsidor#42]
Jag testade att uppdatera mina föreställningar i föreställningsräknaren. Jag upptäckte att den skiter fullständigt i mina tidigare val om jag återvänder till en uppsättning. Eller är det så att ni inte sparar vilka föreställnignar utan bara totalsiffran för varje uppsättning?

# För att återskapa buggen
- Gå till föreställningsräknaren.
- Välj en uppsättning där du sett noll föreställningar.
- Kryssa i att du sett premiären och spara.
- Välj samma uppsättning igen.

## Förväntat beteende:
- Premiärföreställnignen är ikryssad, alla andra föreställningar är urkryssade.

## Observerat beteende
 - Alla föreställningar är ikryssade.

**Comment by Karlinde** [comment]
Nej det verkar vara en bugg som bara uppträder på servern och inte i min lokala utvecklingsmiljön. Jag misstänker att det har att göra med att jag använde sqlite lokalt men servern kör postgresql.

Troligtvis är det ORM-uttrycket som används för att populera infon ifall man varit med på en viss föreställning känsligt för skillnader mellan databasmotorerna. Jag kan försöka skriva om det till något enklare.
