### ISSUE TITLE
Kunna lista styrelser

### ISSUE THREAD

**Issue by Rovanion** [LinkopingsStudentspex/internsidor#57]
Jag skulle vilja ha en sida där man kan lista alla styrelser spexet haft.

**Comment by jonatanmindroad** [comment]
På gång. Kan man kanske få bli en "contributor"?
Ping @Rovanion

**Comment by Rovanion** [comment]
Sådär, nu ska ditt jobbkonto ha fått en inbjudan att bli medlem i organisationen. Ditt privata konto @jonatanskogsfors är redan det.

**Comment by jonatanskogsfors** [comment]
Suck! Kan du inte bara radera hela mig!? Jag insåg inte att jag var inne på fel konto. Det är inte alltid lätt när man bollar multipla konton. Mitt jobbkonto har inget här att göra.

**Comment by Rovanion** [comment]
Sådär, nu är du oinbjuden :D

**Comment by jonatanskogsfors** [comment]
Så angående den här featuren. Istället för att visa vara styrelse gjorde jag precis som med uppsättningar. Man väljer ett verksamhetsår och sedan kan man se alla grupper som ligger på föreningen.

**Comment by jonatanskogsfors** [comment]
För att se bara styrelsen tänker jag att det kan vara värt att fundera ut något generellt som gäller alla grupper. Visa en grupp och pilar för att gå till nästa respektive föregående år. Kan ju vara intressant att tex se bara orkestern och snabbt välja mellan åren.
