### ISSUE TITLE
Bristande logik vid färgning av uppsättningslistor

### ISSUE THREAD

**Issue by jonatanskogsfors** [LinkopingsStudentspex/internsidor#59]
I uppsättningslistorna används bakgrundsfärg för att markera två helt separata saker:
- Rött för att man inte betalat medlemsavgift
- Gult för att personuppgifterna är dolda

Med nuvarande logik på sidan gäller följande:
- Om en gul person inte har betalat medlemsavgiften syns inte detta
- Om man inte är admin ser man färgen gult men inte förklaringen vad den betyder

Eftersom inga personuppgifter skrivs ut i den vyn (utöver namn och medlemsnummmer) så kanske man antingen kan strunta i att markera detta eller göra det mer subtilt. Inne på detaljvyn för personen kan man vara tydligare.

**Comment by Rovanion** [comment]
Vidare används färgen rött/gult för omvända saker i själva personuppgiftsvyn om jag minns rätt.

**Comment by jonatanskogsfors** [comment]
Men det är bara för att man ska få se hur det är att vara färgblind. Makes you think…

**Comment by Rovanion** [comment]
Lite grupptryck har aldrig skadat :D
